### PR TITLE
added support for BigNatural

### PR DESCRIPTION
**Pull request by fametrano**

### CODE REVIEW

**Comment by fametrano** [comment]
Hi Eric

what about this pull request? If I got it right Luigi's already accepted it, so what is left is your supervision if the BigNatural support I coded is complete.
Then the pull request can be closed.
Please let me know

**Comment by eehlers** [comment]
Hey Nando

No problem I will take a look and let you know.  If it's all right with you I'll do this at the same time that I package the QLXL 1.6 release.

**Comment by eehlers** [comment]
i haven't forgotten this, will look at it before the release.

**Comment by fametrano** [comment]
was this ok?

**Comment by fametrano** [comment]
closing it as too old

**Pull request closed without merging**
